env:
  es6: true
  node: true
extends:
  - airbnb-base
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2020
  sourceType: module
plugins:
  - '@typescript-eslint'
rules:
  linebreak-style:
    - warn
    - windows
  quotes:
    - error
    - single
  semi:
    - error
    - never
