env:
  node: true
  es2020: true
extends:
  - airbnb-base
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2020
  sourceType: module
plugins:
  - '@typescript-eslint'
settings:
  import/resolver:
    node:
      extensions:
        - .js
        - .jsx
        - .ts
        - .tsx
rules:
  '@typescript-eslint/no-unused-vars': error
  import/no-unresolved:
    - error
    -
      ignore:
        - \.js$
  import/prefer-default-export: off
  linebreak-style:
    - warn
    - windows
  no-unused-vars: off
  quotes:
    - error
    - single
  semi:
    - error
    - never
